service:
  golangci-lint-version: 1.12.x
  analyzed-paths:
    - ./...
  prepare:
    - make install
    - go generate

linters:
  enable:
    - deadcode
    - gocyclo
    - golint
    - varcheck
    - structcheck
    - maligned
    - errcheck
    - dupl
    - ineffassign
    - interfacer
    - unconvert
    - goconst
    - gosec
    - megacheck