name: golangci-lint

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      - run: echo "::add-path::$(go env GOPATH)/bin"

      - name: Install
        run: make install

      - name: Install tools
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $(go env GOPATH)/bin

      - name: run tools
        run: |
          golangci-lint run --out-format line-number --config=.github/.golangci.yml |\
          reviewdog -f=golangci-lint -name="golangci" -reporter="github-pr-review" -level="info"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
